### ISSUE TITLE
C header file for raspberry

### ISSUE THREAD

**Issue by bcelary** [MajenkoLibraries/ICSC#1]
Great library. I need to hook it up with RasPi, could you please add or provide a link to a header file mentioned on the sourceforge website?

**Comment by majenkotech** [comment]
The Linux code I had written didn't work.  It needs a complete re-write in C++. It's on my list of thing to do.

**Comment by bbbowden** [comment]
For what it's worth, I took the existing linux c code and adapted it to C# for a Windows .Net middleware application.  This was awhile ago so I don't exactly remember all the issues I had but they mostly had to do with threading.  Now, I am moving my application to RPi too so it looks like I'll have a go at modifying the linux version.  Could you expand on the issues you had as to why it didn't work?

**Comment by rytisa** [comment]
Is the any progress on ICSC for RasPi? If not, maybe somebody could recommend similar alternative, library which could be used for RS485 communication between multiple Arduinos and RasPi?

**Comment by bbbowden** [comment]
I was successful getting the library to work in my RasPi application, more than happy to share.

**Comment by rytisa** [comment]
This would be great!  Could you send it to me by email or provide the
download link?

Btw, I try to use CH340 usb to rs485 dongle. Which way you connect RasPi to
rs485?

Thanks a lot!!!
2015 rugs. 3 10:05 popiet "bbbowden" notifications@github.com rašė:

**Comment by therobotworkshop** [comment]
Hi bbbowden,
I would love to get it working on a rpi too please.
I currently have it running on 20 Arduinos triggering audio, servos, lights, doors etc.
Works a treat.
I want to have the rpi as an main viewer looking at what's on and what's not.
A very nice Library.
Rod

**Comment by bbbowden** [comment]
Sounds very similar to the way I am using the library.  I will try to fork the project and upload my version.

Brett.

**Comment by majenkotech** [comment]
I have been working on the beginnings of a Python module.  I have sending working, but haven't yet had a chance to test the reception.  I'll see about pushing that up here too.

**Comment by bbbowden** [comment]
Ok, I've added a fork with my version.  Taking a look at the current master project, I've obviously not included a lot of the functionality (broadcast, sending different type values, etc).  But hopefully, this is a start for a linux based version of this very helpful library.

**Comment by therobotworkshop** [comment]
Awesome Thanks guys!

**Comment by therobotworkshop** [comment]
Actually I did find something the other day and I have seen it before.
I tried sending from one Arduino to another to play audio.
It defiantly sent ok but the other end would not receive it.
It would receive from other units ok.
Is there a limit to how many command functions can be called?
It seemed to be the tenth one that didn't work?

Rod

**Comment by majenkotech** [comment]
Yes. If you don't have dynamic memory mode enabled in ICSC.h there is a limit of 10 commands:

```
#define MAX_COMMANDS 10
```

**Comment by therobotworkshop** [comment]
Cheers
