### ISSUE TITLE
how to change hardware serial to software serial?

### ISSUE THREAD

**Issue by KangKamal** [MajenkoLibraries/ICSC#11]
it's just can do through hardware serial? can i change that default pin to software serial(not serial1 or serial2), because i'm using arduino uno for my trial...

**Comment by majenkotech** [comment]
Just use software serial instead of hardware serial.

ICSC doesn't care what you use, as long as it's a Stream object.

**Comment by KangKamal** [comment]
my slave code :
`SoftwareSerial mySerial (7,8);
setup(){
ICSC.begin(201, 115200, 2, &mySerial);
}`

no error detected, but not working at all... trying to move another pin and changing baudrate didn't respond any command.

**Comment by KangKamal** [comment]
**[SOLVED]** i'm using this [https://github.com/MajenkoLibraries/ICSC/pull/2/files](url) ,
but the problem is data going to random or can't respond fast, so i stop using softwareSerial for my trial, and change pin to hardwareSerial.

**Comment by majenkotech** [comment]
You're obviously using a phenomenally ancient version of ICSC. That way of dealing with the serial objects hasn't been in use for years. Get the latest version of the code **from here** and follow the examples and instructions in *docs*.
