### ISSUE TITLE
ICSC and STM32F103C8T6

### ISSUE THREAD

**Issue by softy2k** [MajenkoLibraries/ICSC#15]
Hello ! 
I apologize if this is wrong place to put it here.
ICSC is a great library. Work perfectly with Arduino.

**From ICSC/example, I compiled PingMaster.ino for Arduino Uno :** 
Sketch uses 3682 bytes (11%) of program storage space. Maximum is 32256 bytes.
Global variables use 327 bytes (15%) of dynamic memory, leaving 1721 bytes for local variables. Maximum is 2048 bytes.

**I tryed to compile (Arduino IDE 1.8.6) ICSC for STM32F103C8 but something is incompatible:**
Sketch uses 75680 bytes (115%) of program storage space. Maximum is 65536 bytes.
Global variables use 6544 bytes (31%) of dynamic memory, leaving 13936 bytes for local variables. Maximum is 20480 bytes.
Sketch too big;

How can we use this library with TM32F103C8 ?
Can you please help me ?

Thank you.

**Comment by majenkotech** [comment]
No, I can't help you. I have never used those chips, and for it to compile at 115% in size there must be something fundamentally broken with the compilation process.  You should ask on a forum associated with using the STM32 in the Arduino environment.
