### ISSUE TITLE
`ICSC.send` to station 9 is received by all registered stations

### ISSUE THREAD

**Issue by efatsi** [MajenkoLibraries/ICSC#3]
I have 11 Arduinos talking to each other with ICSC, when they all boot up the master node runs through a loop to make sure the rest are alive by sending a ping to each one in succession and ensuring a pong comes back.

When the master gets to `ICSC.send(9, 'P', 'p');`, all of the stations receive the message instead of just the 9th.

**Comment by FrankOcean11** [comment]
will this be something i can use for my humanoid application ?> i want to run commands from a AI running in VS2013 via serial to the on board mcu's "Arduino's"

the AI is taken commands using the speech recognition followed by the synthesizer & the string command sent by one of the designed COM Ports on the PC where Arduino will be awaiting "listening"
